#avaliable screensavers: snow, balls, 3d_model
screensaver = "balls"
fullscreen = true

[snow]
snowflake_count = 7500

[balls]
speed = 0.1
count = 10000
size = 0.05
#random - a random color, it changes when balls bounce off of each other
#color - a flat color.
#temperature - makes it so the color's hue depends on a given particle's velocity. may impact perfromance
#infection - one ball is chosen, it has a different color to every other ball and it is infected. ever ball that touches an infected ball becomes infected itself. after all balls get infected a new one is chosen
color_mode = "infection"
color = "#22ff22"
#makes it so the opacity of a ball is dependent on the ammount of balls in the surrounding regions. if the region size is lower, the contrast will be higher
show_density = true
#used for the density color mode. the determines what density is considered "high"
target_display_density = 10.0
#for optimisation's sake, the space is divided up into regions, of which the size depends on the ball size, and this value. increase this value for spare simulations, decrease it for dense ones
#do not decrease it under 0.5, otherwise the simulation will start glitching
#if you want to learn more look up "spatial hashing"
region_size = 1.0
#whether the balls should slow down/speed up if the average speed is higher/lower than the configured speed.
correct_ball_velocity = true

[3d_model]
model = "apple"
model_scale = 1.0
spin_speed = 1.0
bounce_speed = 1.0
bounce_height = 0.2